import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { getUser, completeOnboarding } from '../services/api';
import { useNavigate } from 'react-router-dom';

export default function Profile() {
  const { user, login, logout } = useAuth();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const [form, setForm] = useState({
    age: '',
    profession: '',
    monthly_income: '',
    fixed_expenses: '',
  });

  useEffect(() => {
    if (user?.user_id) {
      getUser(user.user_id)
        .then((r) => {
          setForm({
            age: r.data.age || '',
            profession: r.data.profession || '',
            monthly_income: r.data.monthly_income || '',
            fixed_expenses: r.data.fixed_expenses || '',
          });
        })
        .catch((err) => {
          console.error("Failed to fetch user data:", err);
          setError("Failed to load profile data.");
        })
        .finally(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, [user]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    setError('');
    setMessage('');
    try {
      await completeOnboarding(user.user_id, {
        age: parseInt(form.age) || null,
        profession: form.profession,
        monthly_income: parseFloat(form.monthly_income) || null,
        fixed_expenses: parseFloat(form.fixed_expenses) || null,
        // risk_profile is generated by backend
      });
      // update context if needed
      login({
        ...user,
        onboarding_completed: true,
      });
      setMessage('Profile saved successfully!');
      // Short delay, then navigate to dashboard
      setTimeout(() => navigate('/dashboard'), 1500);
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to save profile. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="loading-spinner">Loading...</div>;
  }

  return (
    <div className="page">
      <div className="topbar">
        <div>
          <div className="page-title">My Profile</div>
          <div className="page-sub">Manage your personal and financial details</div>
        </div>
      </div>
      
      <div style={{ maxWidth: '480px' }}>
        <div className="card">
          {error && <div className="auth-error" style={{ marginBottom: '16px' }}>{error}</div>}
          {message && <div style={{ background: '#eaf3de', color: '#3b6d11', padding: '10px 14px', borderRadius: '8px', marginBottom: '16px', fontSize: '13px' }}>{message}</div>}
          
          <form onSubmit={handleSubmit}>
            <div className="field">
              <label>Age</label>
              <input
                type="number"
                placeholder="e.g. 28"
                value={form.age}
                onChange={(e) => setForm({ ...form, age: e.target.value })}
                required
              />
            </div>
            <div className="field">
              <label>Profession</label>
              <input
                type="text"
                placeholder="Software Engineer"
                value={form.profession}
                onChange={(e) => setForm({ ...form, profession: e.target.value })}
                required
              />
            </div>
            <div className="field">
              <label>Monthly Income (₹)</label>
              <input
                type="number"
                placeholder="0.00"
                value={form.monthly_income}
                onChange={(e) => setForm({ ...form, monthly_income: e.target.value })}
                required
              />
            </div>
            <div className="field">
              <label>Fixed Expenses (₹ / Month)</label>
              <input
                type="number"
                placeholder="0.00"
                value={form.fixed_expenses}
                onChange={(e) => setForm({ ...form, fixed_expenses: e.target.value })}
                required
              />
            </div>

            <div style={{ marginTop: '24px' }}>
              <button className="btn btn-primary" type="submit" disabled={saving} style={{ width: '100%', justifyContent: 'center' }}>
                {saving ? 'Saving...' : 'Save Profile'}
              </button>
            </div>
          </form>
        </div>

        <div style={{ marginTop: '24px', textAlign: 'center' }}>
          <button 
            className="btn btn-secondary" 
            onClick={() => { logout(); navigate('/login'); }} 
            style={{ width: '100%', justifyContent: 'center', borderColor: '#fcebeb', color: '#a32d2d', background: '#fff' }}
          >
            Log out
          </button>
        </div>
      </div>
    </div>
  );
}
